my_string = input('Введите текст: ')
number_of_characters = len(my_string)
print(number_of_characters)
print(my_string .upper())
print(my_string .lower())
print(my_string .replace(' ', ''))
print(my_string [-1])
